language: c

sudo: required

env:
  - CFG=--enable-debug
  - CFG=--disable-disable

os:
  - linux
  - os

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libnova-dev libcurl4-openssl-dev libjson0-dev libdb4.8-dev

install:
  - autoreconf -i

script:
  - ./configure $CFG && make && make test