language: c

sudo: required

env:
  - CFG_DEBUG=--enable-debug
  - CFG_DEBUG=--disable-debug
  - CFG_GEO=--disable-geonames
  - CFG_GEO=--enable-geonames

os:
  - linux
  - os

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libnova-dev libcurl4-openssl-dev libjson-c-dev

install:
  - autoreconf -i

script:
  - ./configure
  - make

test:
  - make test
